import pandas as pd
import os
from pathlib import Path

WORKFLOW = Path("workflow").resolve()
CONFIG = Path("config").resolve()
RULES = WORKFLOW / "rules"
ENVS = WORKFLOW / "envs"
SCRIPTS = WORKFLOW / "scripts"
RESULTS = Path("results").resolve()
FIGURES = RESULTS / "figures"
TABLES = RESULTS / "tables"
LOGS = Path("logs/rules").resolve()
ASM_DIR = Path("data/assembly").resolve()
BAKTA_DB = os.environ["BAKTA_DB"]


# configfile: CONFIG / "config.yaml"


samplesheet = pd.read_csv(
    CONFIG / "samplesheet.csv", index_col="sample_id", comment="#"
)

expected_files = set()
for sample_id in samplesheet.index:
    expected_files.add(RESULTS / "annotation" / sample_id / f"{sample_id}.gff3")
    expected_files.add(RESULTS / f"typing/AMR/{sample_id}/summary_matches.txt")
    expected_files.add(RESULTS / f"typing/mlst/{sample_id}/mlst.tsv")
    expected_files.add(RESULTS / f"QC/CheckM2/{sample_id}_checkm2.tsv")
    expected_files.add(RESULTS / f"typing/mob_suite/{sample_id}/mobtyper_results.txt")
    expected_files.add(RESULTS / f"typing/abricate/{sample_id}.abricate.tsv")


rule all:
    input:
        expected_files,


include: RULES / "annotation.smk"
include: RULES / "typing.smk"
include: RULES / "qc.smk"
